[build-system]
build-backend = "setuptools.build_meta"
requires = ["Django"]

[project.urls]
Homepage = "https://github.com/bigvisionai/pyOpenAnnotate"
 
[project.scripts]
annotate = "annotation.annotate:main"
showlbls = "tools.visualize:main"